name: provim
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - blosc=1.17.1
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cloudpickle=1.2.2
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.10.0
  - decorator=4.4.1
  - freetype=2.10.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - icu=64.2
  - imageio=2.6.1
  - joblib=0.14.1
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - llvm-openmp=9.0.1
  - llvmlite=0.31.0
  - lz4-c=1.8.3
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mock=3.0.5
  - networkx=2.4
  - numba=0.48.0
  - numexpr=2.7.1
  - numpy=1.17.5
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pillow=7.0.0
  - pip=20.0.2
  - pyimzml=1.2.6
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pytables=3.6.1
  - python=3.8.1
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.12.5
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - setuptools=45.1.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - umap-learn=0.3.10
  - wheel=0.34.1
  - wheezy.template=0.1.167
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip
    - pyqtwebengine
