# -*- coding: utf-8 -*-
"""
********************************
BASIS imput/output sub-package
********************************

The sub-package includes modules for reading and depositing individual MSI data files 
(generated by e.g. HDI) software into hdf5 database file for subsequent pre-processing.
  
"""